### ISSUE TITLE
zqtl for win 10

### ISSUE THREAD

**Issue by yuanzhongshang** [YPARK/zqtl#4]
Hi,
 I have no root account to update the GCC version, is it possible to install this package under the Win10? Would you like to share the detailed instructions to install it? Thanks

**Comment by YPARK** [comment]
Sorry. I don't have a window machine.  Can you install linux or try out a virtualbox in your window machine?  I think you can easily access any of them.  Another option is to consider conda or dotkit.  It is quite a big topic to discuss here.
