### ISSUE TITLE
Unable to install in R - ERROR: compilation failed for package ‘zqtl’

### ISSUE THREAD

**Issue by evansad** [YPARK/zqtl#6]
I've used devtools::install_github("YPARK/zqtl") in R directly, and failed with error message:

Downloading GitHub repo YPARK/zqtl@master
checking DESCRIPTION meta-information ...6/klc42n4j7sl75sgtz7bwj3d00000gp/T/RtmpdlueBw/remotes2bc84f5c564e/YPARK-zqtl-1b91841/DESCRIPTION’ ...
* installing *source* package ‘zqtl’ ...
** libs
g++-6 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppEigen/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppProgress/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppZiggurat/include" -I/usr/local/include -fPIC -O3 -std=c++14 -c rcpp_plink.cc -o rcpp_plink.o
/bin/sh: g++-6: command not found
make: *** [rcpp_plink.o] Error 127
ERROR: compilation failed for package ‘zqtl’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/zqtl’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/zqtl’
Error in i.p(...) : 
(converted from warning) installation of package ‘/var/folders/k6/klc42n4j7sl75sgtz7bwj3d00000gp/T//RtmpdlueBw/file2bc87cfab206/zqtl_1.4.0.tar.gz’ had non-zero exit status

gcc is installed which is in directory /usr/local/bin.

**Comment by YPARK** [comment]
Can you share your .R/Makevar?
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-Makevars

**Comment by YPARK** [comment]
Test g++ in your command line
